bpm: 120
voices:
  - name: saw1
    type: SAW
  - name: square_gtr
    type: SQUARE
  - name: bass
    type: TRIANGLE
drumset:
  - piece: kick
    sample: samples/kick.wav
    mapTo: C2
    gain: 0.8
  - piece: snare
    sample: samples/snare.wav
    mapTo: D2
    gain: 0.5
parts:
  - id: intro
    repeat: 1
    once: true
    tracks:
      - name: GTR
        gain: 0.8
        voice: saw1
        src: midi/gtr_intro.mid
      - name: GTR_2
        gain: 0.5
        voice: square_gtr
        src: midi/gtr_intro_2.mid
      - name: DRUMS
        
    - id: verse
      repeat: 4
      tracks:
        - name: GTR
          gain: 0.9
          voice: saw1
          src: midi/gtr_intro.mid
    - id: bridge
      repeat: 1
      tracks:
        - name: GTR
          gain: 0.9
          voice: saw1
          src: midi/gtr_intro.mid
